### ISSUE TITLE
When will a "readme" be forthcoming?

### ISSUE THREAD

**Issue by theofficejackpot** [mxenabled/ios-connect-demo#3]
Hi, thanks for the project.  Can you give some step by step instructions on how to get this implemented as opposed to comments embedded in the code?  Is there a way I can communicate directly with you to try and get this up and running in my sandbox?  Thanks,

**Comment by sambev** [comment]
Hi @theofficejackpot. I just made a rough draft MR for the README. https://github.com/mxenabled/ios-connect-demo/pull/4/files

Any feedback is greatly appreciated!

**Comment by sambev** [comment]
Going to close this as we now have a readme. Feel free to open another issue if you have any specific questions.
